# Generated by Django 4.2.2 on 2023-07-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("serviceWeConnect", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Calandrier",
        ),
    ]
