# Generated by Django 4.2.2 on 2023-07-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("serviceWeConnect", "0002_delete_calandrier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clandrier",
            fields=[
                (
                    "idCland",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "idClub",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("password", models.CharField(max_length=500)),
                ("photo", models.ImageField(upload_to="images/clubs/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "clandrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="serviceWeConnect.clandrier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "idMembre",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="images/clubs/")),
                ("password", models.CharField(max_length=500)),
                (
                    "clandrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="serviceWeConnect.clandrier",
                    ),
                ),
                ("clubs", models.ManyToManyField(to="serviceWeConnect.club")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "idEvent",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("nbparticipant", models.IntegerField()),
                ("nbLike", models.IntegerField(blank=True)),
                ("photo", models.ImageField(upload_to="images/clubs/")),
                ("dateEvent", models.DateTimeField()),
                ("heureEvent", models.TimeField()),
                ("rate", models.IntegerField(blank=True)),
                ("nbRate", models.IntegerField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="serviceWeConnect.club",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clandrier",
            name="events",
            field=models.ManyToManyField(to="serviceWeConnect.event"),
        ),
    ]
