# Generated by Django 4.2.2 on 2023-07-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("serviceWeConnect", "0005_alter_event_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="clandrier",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="serviceWeConnect.clandrier",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="serviceWeConnect.club",
            ),
        ),
    ]
