# Generated by Django 4.2.2 on 2023-07-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "serviceWeConnect",
            "0007_alter_clandrier_events_alter_club_clandrier_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClandrierClub",
            fields=[
                (
                    "idCland",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClandrierMembre",
            fields=[
                (
                    "idCland",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "events",
                    models.ManyToManyField(blank=True, to="serviceWeConnect.event"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="club",
            name="clandrier",
        ),
        migrations.RemoveField(
            model_name="membre",
            name="clandrier",
        ),
        migrations.DeleteModel(
            name="Clandrier",
        ),
        migrations.AddField(
            model_name="clandriermembre",
            name="membre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="serviceWeConnect.membre",
            ),
        ),
        migrations.AddField(
            model_name="clandrierclub",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="serviceWeConnect.club",
            ),
        ),
        migrations.AddField(
            model_name="clandrierclub",
            name="events",
            field=models.ManyToManyField(blank=True, to="serviceWeConnect.event"),
        ),
    ]
