# Generated by Django 4.2.3 on 2023-08-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0008_clandrierclub_clandriermembre_remove_club_clandrier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='nbLike',
        ),
        migrations.RemoveField(
            model_name='event',
            name='nbRate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='membre',
        ),
        migrations.AddField(
            model_name='club',
            name='nbEvents',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='nbMembers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='familyName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='firstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='userName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceWeConnect.club'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateEvent',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Calandrier',
            fields=[
                ('idCland', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('events', models.ManyToManyField(to='serviceWeConnect.event')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='idCland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceWeConnect.calandrier'),
        ),
        migrations.AddField(
            model_name='membre',
            name='idCland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceWeConnect.calandrier'),
        ),
    ]
