# Generated by Django 4.2.3 on 2023-08-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0009_remove_event_nblike_remove_event_nbrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='clubs',
            field=models.ManyToManyField(blank=True, to='serviceWeConnect.club'),
        ),
    ]
