# Generated by Django 4.2.3 on 2023-08-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0010_alter_membre_clubs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='idMembre',
            new_name='idMember',
        ),
    ]
