# Generated by Django 4.2.3 on 2023-08-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0012_remove_membre_clubs_membre_club_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='club',
            new_name='clubs',
        ),
    ]
