# Generated by Django 4.2.3 on 2023-08-22 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0014_remove_membre_clubs_membre_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceWeConnect.event'),
        ),
    ]
