# Generated by Django 4.2.3 on 2023-08-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0016_rename_calandrier_calandrierevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='idCland',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='idCland',
        ),
        migrations.DeleteModel(
            name='CalandrierEvent',
        ),
    ]
