# Generated by Django 4.2.3 on 2023-08-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0019_membre_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='events',
        ),
    ]
