# Generated by Django 4.2.4 on 2023-09-03 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0028_rename_heureevent_event_heureeventstart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clandrierclub',
            name='club',
        ),
        migrations.RemoveField(
            model_name='clandriermembre',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='club',
            name='idCland',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='idCland',
        ),
        migrations.AddField(
            model_name='clandrierclub',
            name='clubs',
            field=models.ManyToManyField(blank=True, to='serviceWeConnect.club'),
        ),
        migrations.AddField(
            model_name='clandriermembre',
            name='member',
            field=models.ManyToManyField(blank=True, to='serviceWeConnect.membre'),
        ),
        migrations.AddField(
            model_name='club',
            name='ClandC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceWeConnect.clandrierclub'),
        ),
        migrations.AddField(
            model_name='membre',
            name='ClandM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceWeConnect.clandriermembre'),
        ),
    ]
