# Generated by Django 4.2.3 on 2023-09-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0029_remove_clandrierclub_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='link_fb',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='link_insta',
            field=models.URLField(null=True),
        ),
    ]
