# Generated by Django 4.2.3 on 2023-09-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0030_club_link_fb_club_link_insta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='link_fb',
            new_name='linkFb',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='link_insta',
            new_name='linkInsta',
        ),
    ]
