# Generated by Django 4.2.3 on 2023-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0031_rename_link_fb_club_linkfb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='linkFb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='linkInsta',
            field=models.URLField(blank=True, null=True),
        ),
    ]
