# Generated by Django 4.2.3 on 2023-07-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calandrier',
            fields=[
                ('idCland', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('events', models.CharField(max_length=100)),
            ],
        ),
    ]
