# Generated by Django 4.2.2 on 2023-07-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("serviceWeConnect", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "idNotification",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("titre", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("categorie", models.CharField(max_length=100)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="serviceWeConnect.membre",
                    ),
                ),
            ],
        ),
    ]
