# Generated by Django 4.2.2 on 2023-07-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceWeConnect", "0004_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="photo",
            field=models.ImageField(upload_to="images/events/"),
        ),
    ]
