# Generated by Django 4.2.2 on 2023-07-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("serviceWeConnect", "0006_alter_club_clandrier_alter_event_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clandrier",
            name="events",
            field=models.ManyToManyField(blank=True, to="serviceWeConnect.event"),
        ),
        migrations.AlterField(
            model_name="club",
            name="clandrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="serviceWeConnect.clandrier",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="password",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="photo",
            field=models.ImageField(null=True, upload_to="images/clubs/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="serviceWeConnect.club",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="dateEvent",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="heureEvent",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="nbLike",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="nbRate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="nbparticipant",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="photo",
            field=models.ImageField(null=True, upload_to="images/events/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
