# Generated by Django 4.2.3 on 2023-08-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0011_rename_idmembre_membre_idmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='clubs',
        ),
        migrations.AddField(
            model_name='membre',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceWeConnect.club'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
