# Generated by Django 4.2.3 on 2023-08-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0013_rename_club_membre_clubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='clubs',
        ),
        migrations.AddField(
            model_name='membre',
            name='clubs',
            field=models.ManyToManyField(blank=True, to='serviceWeConnect.club'),
        ),
    ]
