# Generated by Django 4.2.3 on 2023-08-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0015_notification_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calandrier',
            new_name='CalandrierEvent',
        ),
    ]
