# Generated by Django 4.2.3 on 2023-08-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0017_remove_club_idcland_remove_membre_idcland_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalandrierEvent',
            fields=[
                ('idCland', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('events', models.ManyToManyField(to='serviceWeConnect.event')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='idCland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceWeConnect.calandrierevent'),
        ),
        migrations.AddField(
            model_name='membre',
            name='idCland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceWeConnect.calandrierevent'),
        ),
    ]
