# Generated by Django 4.2.3 on 2023-08-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0018_calandrierevent_club_idcland_membre_idcland'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='events',
            field=models.ManyToManyField(blank=True, to='serviceWeConnect.event'),
        ),
    ]
