# Generated by Django 4.2.3 on 2023-08-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0020_remove_membre_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='phoneNumber',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
