# Generated by Django 4.2.3 on 2023-08-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0022_remove_membre_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
