# Generated by Django 4.2.3 on 2023-08-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0023_membre_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='username',
        ),
    ]
