# Generated by Django 4.2.3 on 2023-08-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeConnect', '0025_membre_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nbMax',
            field=models.IntegerField(null=True),
        ),
    ]
